### ISSUE TITLE
include relative static files path 

### ISSUE THREAD

**Issue by salimchami** [chris-bailey/spring-boot-thymeleaf-heroku-template#1]
Hello ! 
I'm using JHipster and searching for an example of templating emails with thymleaf.
My problem is that the css and js (static files) aren't injected into my templates... 
In your application, i don't see a class to send mails... Is there something I missed ? 

In your template, you use this : 

`<link href="../../static/css/bootstrap.min.css" th:href="@{/css/bootstrap.min.css}" rel="stylesheet" media="screen" />`

My code is exactly the same that yours... i have added jodatime-thymeleaf and thymeleaf-extras.
But when i try to use it, i have this error : 

`org.thymeleaf.exceptions.TemplateProcessingException: Link base "/css/email.css" cannot be context relative (/) or page relative unless you implement the org.thymeleaf.context.IWebContext interface (context is of class: org.thymeleaf.context.Context) (contactEmailToSchoolme:10)`

my template : 

`<link href="../static/css/email.css" th:href="@{/css/email.css}" rel="stylesheet" media="screen" />`

and my folders : 

```
--- resources
          | -------- i18n
          | -------- mails
          | -------- static
                            | -------- css
                            | -------- js
```

What is the problem here ? 
Thanks !

**Comment by chris-bailey** [comment]
The template isn't set up for email.  The issue your having with your project isn't related to an issue in this project so I'm going to close this issue.  Please email me through my contact page at 'chrisbaileydeveloper.com' and I'll try to help you out.

**Comment by AmanKishan** [comment]
I also facing the same issue, please help me out
