### ISSUE TITLE
Error on Upgrade Spring Boot Version into 1.5.19.RELEASE

### ISSUE THREAD

**Issue by hendisantika** [chris-bailey/spring-boot-thymeleaf-heroku-template#2]
Nice repo.

I want to try to upgrade your repo.
But, I was trying on my local first.
Then Error on Upgrade Spring Boot Version into 1.5.19.RELEASE.

Could You try to upgrade your Spring Boot Version into 1.5.19.RELEASE?

Here my repo based on yours --> https://github.com/hendisantika/springboot-thymeleaf-heroku-template

Thanks

**Comment by chris-bailey** [comment]
Hi Hendi,
Due to professional responsibilities I'm unable to keep this repo
up-to-date.

Best regards,
Chris

**Comment by hendisantika** [comment]
Ooo... Ya ya ya.

OK.

Thanks.
Best Regards,
Hendi Santika
